// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	CreateStorage(ctx context.Context, arg CreateStorageParams) (Storage, error)
	GetStorage(ctx context.Context, arg GetStorageParams) (Storage, error)
	ListStorage(ctx context.Context) ([]Storage, error)
	UpdateStorage(ctx context.Context, arg UpdateStorageParams) (Storage, error)
}

var _ Querier = (*Queries)(nil)
